blogs/urls.py
from django.urls import path

from blogs.views import BlogsListView, BlogDetailView

app_name = 'blogs'

urlpatterns = [
    path('', BlogsListView.as_view(), name='list'),
    path('detail/<int:pk>/', BlogDetailView.as_view(), name='detail'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('products/', include('products.urls', namespace='products')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pages/urls.py
from django.urls import path

from pages.views import HomePageView, ContactTemplateView

app_name = 'pages'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('contact/', ContactTemplateView.as_view(), name='contact'),
]

products/urls.py
from django.urls import path

from products.views import ProductsListView

app_name = 'products'

urlpatterns = [
    path('', ProductsListView.as_view(), name='list'),
]

blogs/models.py
from django.db import models


class AuthorModel(models.Model):
    name = models.CharField(max_length=128)
    image = models.ImageField(upload_to='blog-authors')
    about = models.TextField()
    position = models.CharField(max_length=128)
    profession = models.CharField(max_length=128)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'author'
        verbose_name_plural = 'authors'


class BlogCategoryModel(models.Model):
    name = models.CharField(max_length=128)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'


class BlogTagModel(models.Model):
    name = models.CharField(max_length=128)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'tag'
        verbose_name_plural = 'tags'


class BlogModel(models.Model):
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='blog-images')
    content = models.TextField()
    short_info = models.TextField(null=True)
    category = models.ManyToManyField(BlogCategoryModel, related_name='blogs')
    tags = models.ManyToManyField(BlogTagModel, related_name='tags')
    authors = models.ForeignKey(AuthorModel, on_delete=models.CASCADE, related_name='blogs')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'blog'
        verbose_name_plural = 'blogs'

pages/models.py
from django.db import models


class ContactModel(models.Model):
    name = models.CharField(max_length=128)
    email = models.EmailField()
    subject = models.CharField(max_length=255, null=True, blank=True)
    message = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Contact'
        verbose_name_plural = 'Contacts'

products/models.py
from django.db import models

# Create your models here.

blogs/views.py
import self
from django.views.generic import ListView, DetailView

from blogs.models import BlogModel, BlogCategoryModel, BlogTagModel


class BlogsListView(ListView):
    template_name = 'blogs/blog-list.html'
    context_object_name = 'blogs'
    model = BlogModel

    def get_context_data(self, *, object_list=None, **kwargs):
        blogs = BlogModel.objects.all()
        cat = self.request.GET.get('cat')
        if cat:
            blogs = blogs.filter(category=cat)

        context = {
            "blogs": blogs,
            "category": BlogCategoryModel.objects.all(),
            "tags": BlogTagModel.objects.all(),
            "famous_blogs": BlogModel.objects.all().order_by('created_at')[:2],
        }
        return context


class BlogDetailView(DetailView):
    template_name = 'blogs/blog-detail.html'
    context_object_name = 'blog'
    model = BlogModel

    def get_context_data(self, *, object_list=None, **kwargs):
        context = {
            "category": BlogCategoryModel.objects.all(),
            "blog": BlogModel.objects.get(pk=self.kwargs['pk']),
            "tags": BlogTagModel.objects.all(),
            "famous_blogs": BlogModel.objects.all().order_by('created_at')[:2],
            "related_blogs": BlogModel.objects.filter(category__in=self.object.category.all())[:3]
        }
        return context

pages/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView

from pages.form import ContactModelForm


class HomePageView(TemplateView):
    template_name = 'home.html'


class ContactTemplateView(CreateView):
    template_name = 'contact.html'
    form_class = ContactModelForm
    success_url = '/'

products/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class ProductsListView(TemplateView):
    template_name = 'products/products_list.html'

templates/base.html
{% load static %}
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]><html class="ie ie9" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<!--<![endif]-->
<html lang="en">


<!-- blogs-list-sidebar-left10:09-->
<head>
    <!-- Basic Page Needs -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Furnitica - Minimalist Furniture HTML Template</title>

    <meta name="keywords" content="Furniture, Decor, Interior">
    <meta name="description" content="Furnitica - Minimalist Furniture HTML Template">
    <meta name="author" content="tivatheme">


    <!-- Mobile Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,500,600,700" rel="stylesheet">

    <!-- Vendor CSS -->
    <link rel="stylesheet" href="{% static 'libs/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'libs/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'libs/nivo-slider/css/nivo-slider.css' %}">
    <link rel="stylesheet" href="{% static 'libs/nivo-slider/css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'libs/nivo-slider/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'libs/font-material/css/material-design-iconic-font.min.css' %}">
    <link rel="stylesheet" href="{% static 'libs/slider-range/css/jslider.css' %}">
    <link rel="stylesheet" href="{% static 'libs/owl-carousel/assets/owl.carousel.min.css' %}">

    <!-- Template CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/reponsive.css' %}">
</head>

<body
        {% if '/blogs/' == request.path %}
        id="blog-list-sidebar-left" class="blog"
        {% elif 'products' in request.path %}
        id="product-sidebar-left" class="product-grid-sidebar-left"
        {% elif 'contact' in request.path %}
        id="contact" class="blog"
        {% elif 'blogs/detail' in request.path %}
        id="blog-detail" class="blog"
        {% endif %}
>
    {% include 'layouts/header-base.html' %}

    <!-- main content -->
    {% block content %}
    {% endblock %}

    <!-- footer -->
    {% include 'layouts/footer.html' %}

    <!-- back top top -->
    <div class="back-to-top">
        <a href="#">
            <i class="fa fa-long-arrow-up"></i>
        </a>
    </div>

    <!-- menu mobie left -->
   {% include 'layouts/menu-mobile-left.html' %}

    <!-- menu mobie right -->
    {% include 'layouts/menu-mobile-right.html' %}

    <!-- Page Loader -->
    <div id="page-preloader">
        <div class="page-loading">
            <div class="dot"></div>
            <div class="dot"></div>
            <div class="dot"></div>
            <div class="dot"></div>
            <div class="dot"></div>
        </div>
    </div>

    <!-- Vendor JS -->
    <script src="{% static 'libs/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'libs/popper/popper.min.js' %}"></script>
    <script src="{% static 'libs/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'libs/nivo-slider/js/jquery.nivo.slider.js' %}"></script>
    <script src="{% static 'libs/owl-carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'libs/slider-range/js/tmpl.js' %}"></script>
    <script src="{% static 'libs/slider-range/js/jquery.dependClass-0.1.js' %}"></script>
    <script src="{% static 'libs/slider-range/js/draggable-0.1.js' %}"></script>
    <script src="{% static 'libs/slider-range/js/jquery.slider.js' %}"></script>

    <!-- Template JS -->
    <script src="{% static 'js/theme.js' %}"></script>
</body>


<!-- blogs-list-sidebar-left10:30-->
</html>

templates/blogs/blog-filter.html
{% load static %}
<div class="sidebar-3 sidebar-collection col-lg-3 col-md-3 col-sm-4">

                                        <!-- category -->
                                        <div class="sidebar-block">
                                            <div class="title-block">Categories</div>
                                            <div class="block-content">
                                                {% for cat in category %}
                                                <div class="cateTitle hasSubCategory open level1">
                                                    <a class="cateItem" href="?cat={{ cat.id }}">{{ cat.name }}</a>
                                                </div>
                                                {% endfor %}
                                            </div>
                                        </div>

                                        <!-- recent posts -->
                                        <div class="sidebar-block">
                                            <div class="title-block">Recent Posts</div>
                                            <div class="post-item-content">
                                                {% for blog in famous_blogs %}
                                                <div>
                                                    <div class="late-item first-child">
                                                        <a href="{% url 'blogs:detail' pk=blog.id %}">
                                                            <p class="content-title">{{ blog.title}}</p>
                                                        </a>
                                                        <span>
                                                            <i class="zmdi zmdi-comments"></i>13 comment
                                                        </span>
                                                        <span>
                                                            <i class="zmdi zmdi-calendar-note"></i>{{ blog.created_at }}
                                                        </span>
                                                        <p class="description">{{ blog.short_info }}
                                                        </p>
                                                        <p class="remove">
                                                            <a href="{% url 'blogs:detail' pk=blog.id %}">READ MORE</a>
                                                        </p>
                                                    </div>
                                                </div>
                                                {% endfor %}
                                            </div>
                                        </div>

                                        <!-- product tag -->
                                        <div class="sidebar-block product-tags">
                                            <div class="title-block">
                                                Blog Tags
                                            </div>
                                            <div class="block-content">
                                                <ul class="listSidebarBlog list-unstyled">
                                                    {% for tag in tags %}
                                                    <li>
                                                        <a href="#" title="Show products matching tag Hot Trend">{{ tag.name }}</a>
                                                    </li>
                                                    {% endfor %}
                                                </ul>
                                            </div>
                                        </div>

                                        <!-- advertising -->
                                        <div class="sidebar-block group-image-special">
                                            <div class="effect">
                                                <a href="#">
                                                    <img class="img-fluid" src="{% static 'img/blog/advertising.jpg' %}" alt="banner-2" title="banner-2">
                                                </a>
                                            </div>
                                        </div>

                                    </div>

templates/blogs/blog-list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="main-content">
        <div id="wrapper-site">
            <div id="content-wrapper">
                <div id="main">
                    <div class="page-home">

                        <!-- breadcrumb -->
                        <nav class="breadcrumb-bg">
                            <div class="container no-index">
                                <div class="breadcrumb">
                                    <ol>
                                        <li>
                                            <a href="#">
                                                <span>Home</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <span>Living Room</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <span>Sofa</span>
                                            </a>
                                        </li>
                                    </ol>
                                </div>
                            </div>
                        </nav>
                        <div class="container">
                            <div class="content">
                                <div class="row">
                                    {% include 'blogs/blog-filter.html' %}
                                    <div class="col-sm-8 col-lg-9 col-md-9 flex-xs-first main-blogs">
                                        <h2>Recent Posts</h2>
                                        {% for blog in blogs %}
                                        <div class="list-content row">
                                            <div class="hover-after col-md-5 col-xs-12">
                                                <a href="{% url 'blogs:detail' pk=blog.id %}">
                                                    <img src="{{blog.image.url}}" alt="img">
                                                </a>
                                            </div>
                                            <div class="late-item col-md-7 col-xs-12">
                                                <p class="content-title">
                                                    <a href="{% url 'blogs:detail' pk=blog.id %}">{{ blog.title}}</a>
                                                </p>
                                                <p class="post-info">
                                                    <span>{{ blog.created_at }}</span>
                                                    <span>113 Comments</span>
                                                    <span>{{ blog.author.name }}</span>
                                                </p>
                                                <p class="description">{{ blog.short_info }}
                                                </p>
                                                <span class="view-more">
                                                    <a href="{% url 'blogs:detail' pk=blog.id %}">view more</a>
                                                </span>
                                            </div>
                                        </div>
                                        {% endfor %}
                                        <div class="page-list col">
                                            <ul class="justify-content-center d-flex">
                                                <li>
                                                    <a rel="prev" href="#" class="previous disabled js-search-link">
                                                        Previous
                                                    </a>
                                                </li>
                                                <li class="current active">
                                                    <a rel="nofollow" href="#" class="disabled js-search-link">
                                                        1
                                                    </a>
                                                </li>
                                                <li>
                                                    <a rel="nofollow" href="#" class="disabled js-search-link">
                                                        2
                                                    </a>
                                                </li>
                                                <li>
                                                    <a rel="next" href="#" class="next disabled js-search-link">
                                                        Next
                                                    </a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="main-content">
        <div id="wrapper-site">
            <div id="content-wrapper">

                <!-- breadcrumb -->
                <nav class="breadcrumb-bg">
                    <div class="container no-index">
                        <div class="breadcrumb">
                            <ol>
                                <li>
                                    <a href="#">
                                        <span>Home</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <span>Contact</span>
                                    </a>
                                </li>
                            </ol>
                        </div>
                    </div>
                </nav>
                <div id="main">
                    <div class="page-home">
                        <div class="container">
                            <h1 class="text-center title-page">Contact Us</h1>
                            <div class="row-inhert">
                                <div class="header-contact">
                                    <div class="row">
                                        <div class="col-xs-12 col-sm-4 col-md-4">
                                            <div class="item d-flex">
                                                <div class="item-left">
                                                    <div class="icon">
                                                        <i class="zmdi zmdi-email"></i>
                                                    </div>
                                                </div>
                                                <div class="item-right d-flex">
                                                    <div class="title">Email:</div>
                                                    <div class="contact-content">
                                                        <a href="mailto:support@domain.com">support@domain.com</a>
                                                        <br>
                                                        <a href="mailto:contact@domain.com">contact@domain.com</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-4 col-md-4">
                                            <div class="item d-flex">
                                                <div class="item-left">
                                                    <div class="icon">
                                                        <i class="zmdi zmdi-home"></i>
                                                    </div>
                                                </div>
                                                <div class="item-right d-flex">
                                                    <div class="title">Address:</div>
                                                    <div class="contact-content">
                                                        23 Suspendis matti, Visaosang Building
                                                        <br>District, NY Accums, North American
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-4 col-md-4">
                                            <div class="item d-flex justify-content-end  last">
                                                <div class="item-left">
                                                    <div class="icon">
                                                        <i class="zmdi zmdi-phone"></i>
                                                    </div>
                                                </div>
                                                <div class="item-right d-flex">
                                                    <div class="title">Hotline:</div>
                                                    <div class="contact-content">
                                                        0123-456-78910
                                                        <br>0987-654-32100
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="contact-map">
                                    <div id="map">
                                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3724.3785754726428!2d105.78134315594316!3d21.01753304734255!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x313454ab43c0c4db%3A0xdb6effebd6991106!2sKeangnam+Hanoi+Landmark+Tower!5e0!3m2!1svi!2s!4v1530175498947" allowfullscreen></iframe>
                                    </div>
                                </div>
                                <div class="input-contact">
                                    <p class="text-intro text-center">“Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin, lorem quis bibendum
                                        auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis sed odio sit
                                        amet nibh vultate cursus a sit amet mauris. Proin gravida nibh vel velit auctor aliquet.”
                                    </p>

                                    <p class="icon text-center">
                                        <a href="#">
                                            <img src="{% static 'img/other/contact_mess.png' %}" alt="img">
                                        </a>
                                    </p>

                                    <div class="d-flex justify-content-center">
                                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                                            <div class="contact-form">
                                                <form action="{% url 'pages:contact' %}" method="post" enctype="multipart/form-data">
                                                    {% csrf_token %}
                                                    <div class="form-fields">
                                                        <div class="form-group row">
                                                            <div class="col-md-6">
                                                                <input class="form-control" name="name" placeholder="Your name">
                                                            </div>
                                                            <div class="col-md-6 margin-bottom-mobie">
                                                                <input class="form-control" name="email" type="email" value="" placeholder="Your email">
                                                            </div>
                                                        </div>
                                                        <div class="form-group row">
                                                            <div class="col-md-12 margin-bottom-mobie">
                                                                <input class="form-control" name="subject" type="text" value="" placeholder="Subject">
                                                            </div>
                                                        </div>
                                                        <div class="form-group row">
                                                            <div class="col-md-12">
                                                                <textarea class="form-control" name="message" placeholder="Message" rows="8"></textarea>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div>
                                                        <button class="btn" type="submit" name="submitMessage">
                                                            <img class="img-fl" src="{% static 'img/other/contact_email.png' %}" alt="img">Send message
                                                        </button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/layouts/menu-mobile-left.html
{% load static %}
<div class="mobile-top-menu d-md-none">
        <button type="button" class="close" aria-label="Close">
            <i class="zmdi zmdi-close"></i>
        </button>
        <div class="tiva-verticalmenu block" data-count_showmore="17">
            <div class="box-content block-content">
                <div class="verticalmenu" role="navigation">
                    <ul class="menu level1">
                        <li class="item">
                            <a href="#" class="hasicon" title="BED">
                                <img src="{% static 'img/home/bed.png' %}" alt="img">BED
                            </a>
                        </li>
                        <li class="item">
                            <a href="#" class="hasicon" title="BED GIRL">
                                <img src="{% static 'img/home/bed.png' %}" alt="img">BED GIRL</a>
                        </li>
                        <li class="item">
                            <a href="#" class="hasicon" title="BED BOY">
                                <img src="{% static 'img/home/bed.png' %}" alt="img">BED BOY</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

    </div>